version: '3.8'
services:
  solr:
    image: solr:8.5.2-slim
    ports:
    - '9639:9639'
    - '7091:7091'
    - '1099:1099'
    - '8983:8983'
    volumes:
    - type: bind
      source: ../../target/scriptable-jmx-exporter-1.0.0-alpha1.jar
      target: /opt/java-agents/scriptable-jmx-exporter.jar
    - type: bind
      source: ./scriptable-jmx-exporter-untyped.yaml
      target: /etc/scriptable-jmx-exporter.yaml
    environment:
    - SOLR_OPTS=
      -javaagent:/opt/java-agents/scriptable-jmx-exporter.jar=@/etc/scriptable-jmx-exporter.yaml
      -Dcom.sun.management.jmxremote.ssl=false
      -Dcom.sun.management.jmxremote.authenticate=false
      -Dcom.sun.management.jmxremote.port=7091
      -Dcom.sun.management.jmxremote.rmi.port=1099
    command:
    - solr-demo
