version: '3.8'

services:
  zookeeper:
    image: 'docker.io/bitnami/zookeeper:3-debian-10'
    ports:
    - '2181:2181'
    volumes:
    - 'zookeeper_data:/bitnami'
    environment:
    - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'docker.io/bitnami/kafka:2-debian-10'
    ports:
    - '9092:9092'
    - '9639:9639'
    - '9404:9404'
    - '7091:7091'
    - '1099:1099'
    volumes:
    - 'kafka_data:/bitnami'
    - type: bind
      source: ../../target/scriptable-jmx-exporter-0.0.8-SNAPSHOT.jar
      target: /opt/java-agents/scriptable-jmx-exporter.jar
    - type: bind
      source: ./jmx_prometheus_javaagent-0.13.0.jar
      target: /opt/java-agents/jmx-exporter.jar
    - type: bind
      source: ./scriptable-jmx-exporter.yaml
      target: /etc/scriptable-jmx-exporter.yaml
    - type: bind
      source: ./kafka-2_0_0.yml
      target: /etc/jmx-exporter.yaml
    # - type: bind
    #   source: ./perf-map-agent/out/attach-main.jar
    #   target: /attach-main.jar
    # - type: bind
    #   source: ./perf-map-agent/out/libperfmap.so
    #   target: /libperfmap.so
    - type: bind
      source: ./perf-map.sh
      target: /perf-map.sh
    environment:
    - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    - ALLOW_PLAINTEXT_LISTENER=yes
    - KAFKA_HEAP_OPTS=-Xmx1g -Xms1g
    - |
      KAFKA_OPTS=
      -javaagent:/opt/java-agents/scriptable-jmx-exporter.jar=@/etc/scriptable-jmx-exporter.yaml
      -javaagent:/opt/java-agents/jmx-exporter.jar=9404:/etc/jmx-exporter.yaml
      -Dcom.sun.management.jmxremote.ssl=false
      -Dcom.sun.management.jmxremote.authenticate=false
      -Dcom.sun.management.jmxremote.port=7091
      -Dcom.sun.management.jmxremote.rmi.port=1099
      -Djava.rmi.server.hostname=localhost
    # -XX:+PreserveFramePointer
    depends_on:
    - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
